security:
    providers:
        custom_user_provider:
            id: app.security.custom_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        custom_secured:
                pattern:   ^/
                stateless: true
                custom:      true
                user_checker: custom.security.authentication.checker

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }


    encoders:
           UserCredentialsBundle\Entity\User:
             algorithm: bcrypt
